FROM        --platform=$TARGETOS/$TARGETARCH azul/zulu-openjdk:8

LABEL       author="Vlssu" maintainer="vlssu@vlssu.com"
ENV         DEBIAN_FRONTEND noninteractive

LABEL       org.opencontainers.image.source="https://github.com/SMGoro/yolks"
LABEL       org.opencontainers.image.licenses=MIT

# RUN         sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
#             && sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
#             && sed -i 's/https/http/g' /etc/apt/sources.list \
#             && sed -i 's/http/https/g' /etc/apt/sources.list

# RUN         mkdir -p /etc/apt/keyrings \
#             && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
#             && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
#             && chmod a+r /etc/apt/keyrings/docker.gpg \
#             && chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg

RUN 		apt update --allow-unauthenticated --allow-insecure-repositories -y \
            && apt install -y lsof curl ca-certificates openssl git tar sqlite3 fontconfig libfreetype6 tzdata iproute2 libstdc++6 locales \
            && useradd -m -d /home/container container \
            && locale-gen zh_CN.UTF-8 \
            && apt clean

ENV         LC_ALL=zh_CN.UTF-8
ENV         LANG=zh_CN.UTF-8
ENV         LANGUAGE=zh_CN.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]
